# Generated by Django 2.0.5 on 2018-07-01 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviemania', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='display_picture',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
